name: Using Cypress GH Action

on: push

jobs:
  single-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm start
